In [72]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print(df)
# #set the marks of anjali as null
# df.loc[4,"marks"] = None
# print(df.isnull())
# #column count missing values
# df.isnull().sum()
# #total missing values
# # df.isnull().sum().sum()

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN

#Removal Of Null Values

In [49]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
#removal of null values (by default row)
print('\n')
print("----------Removal of null values----------")
print(df.dropna())
#removal of column with null values
print('\n')
print("----------Removal of column with null values----------")
print(df.dropna(axis=1))

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN


----------Removal of null values----------
       name  roll no  marks
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0


----------Removal of column with null values----------
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

#Replacing Null Values

In [52]:
#replacing null values
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
#filling values --> fill's givenvvalue where value is null
df.fillna(1)

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN

       name  roll no  marks
0   dheeraj      123    1.0
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    1.0

Question

In [71]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
print("_____________________________________")
print('\n')
# #set marks = 100 at place of null
# df["marks"].fillna(100,inplace=True)
# print(df)
#filling null values by mean value
mean = df["marks"].mean()
df["marks"] = df["marks"].fillna(mean)
df

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN
_____________________________________

       name  roll no  marks
0   dheeraj      123   30.0
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   30.0