In [72]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print(df)
# #set the marks of anjali as null
# df.loc[4,"marks"] = None
# print(df.isnull())
# #column count missing values
# df.isnull().sum()
# #total missing values
# # df.isnull().sum().sum()

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN

#Removal Of Null Values

In [49]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
#removal of null values (by default row)
print('\n')
print("----------Removal of null values----------")
print(df.dropna())
#removal of column with null values
print('\n')
print("----------Removal of column with null values----------")
print(df.dropna(axis=1))

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN


----------Removal of null values----------
       name  roll no  marks
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0


----------Removal of column with null values----------
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

#Replacing Null Values

In [52]:
#replacing null values
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
#filling values --> fill's givenvvalue where value is null
df.fillna(1)

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN

       name  roll no  marks
0   dheeraj      123    1.0
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    1.0

Question

In [71]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
print("_____________________________________")
print('\n')
# #set marks = 100 at place of null
# df["marks"].fillna(100,inplace=True)
# print(df)
#filling null values by mean value
mean = df["marks"].mean()
df["marks"] = df["marks"].fillna(mean)
df

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN
_____________________________________

       name  roll no  marks
0   dheeraj      123   30.0
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   30.0

Aggregation

In [87]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
print("_____________________________________")
print("                  MANUALLY                  ")
print('\n')
print("----------Mean----------")
print(df["marks"].mean())
print('\n')
print("----------Sum----------")
print(df["marks"].sum())
print('\n')
print("----------Min----------")
print(df["marks"].min())
print('\n')
print("----------Max----------")
print(df["marks"].max())
print('\n')
print("----------Count----------")
print(df["marks"].count())

print("_____________________________________")
print("                  USING AGGREGATE FUNCTION                  ")
print('\n')
print(df["marks"].agg(["sum","max","min","count","mean"]))

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN
_____________________________________
                  MANUALLY


----------Mean----------
30.0


----------Sum----------
90.0


----------Min----------
20.0


----------Max----------
40.0


----------Count----------
3
_____________________________________
                  USING AGGREGATE FUNCTION


sum      90.0
max      40.0
min      20.0
count     3.0
mean     30.0
Name: marks, dtype: float64

Concat

In [108]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
df1 = pd.read_json(url)
print("____________________________________")
print('\n')
#concatanation(by default --> row)
print("----------Cancatanation By row----------")
print(pd.concat([df,df1]))
#concatanation (by column)
print('\n')
print("----------Cancatanation By Column----------")
df2=pd.concat([df,df1],axis=1)
print(df2)
#change the name of abhishek
print('\n')
print("----------Changing Name----------")
df2.loc[2,"name"] = "ankita"
print(df2)

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN
____________________________________


----------Cancatanation By row----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN


----------Cancatanation By Column----------
       name  roll no  marks      name  roll no  marks
0   dheeraj      123    NaN   dheeraj      123    NaN
1     kunal     1234   20.0     kunal     1234   20.0
2  abhishek    12345   30.0  abhishek    12345   30.0
3   praveen    12356   40.0   praveen    12356   40.0
4    anjali  1234567    NaN    anjali  1234567    NaN


----------Changing Name----------
      name  roll no  marks     name  roll no  marks
0  dheeraj      123    NaN  dheeraj      123    NaN
1    kunal     1234   20.0    kunal     1234   20.0
2   ankita    12345   30.0   ankita    12345   30.0
3  praveen    12356   40.0  praveen    12356   40.0
4   anjali  1234567    NaN   anjali  1234567    NaN