#Pandas In Python

In [ ]:
#List
import pandas as pd
df = pd.Series([10,20,30])
print(df)


print('\n')
print("--------------------")
print('\n')

#Dictoinary
dict = { "name" : ["kunal" , "dheeraj" , "praveen"] ,
          "Age" : [21 , 21 , 20] ,
           "Salary" : [{"In Hand " : 35000 , "CTC" : "2.5lpa"} ,
                      {"In Hand " : 25000 , "CTC" : "2 lpa"} ,
                      {"In Hand " : 15000 , "CTC" : "1 lpa"} ]
}


print(pd.DataFrame(dict))

0    10
1    20
2    30
dtype: int64


--------------------


      name  Age                                Salary
0    kunal   21  {'In Hand ': 35000, 'CTC': '2.5lpa'}
1  dheeraj   21   {'In Hand ': 25000, 'CTC': '2 lpa'}
2  praveen   20   {'In Hand ': 15000, 'CTC': '1 lpa'}

#Save And Load Data From CSV , JSON And Excel

In [ ]:
#CSV
import pandas as pd
print("_____CSV_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.csv"
df = pd.read_csv(url)
print(df)
print('\n')
# from google.colab import drive
# drive.mount('/content/drive')
# url = "/content/drive/MyDrive/file1.csv"
# df = pd.read_csv(url)
# print(df)


#Json
print("_____JSON_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.json"
df = pd.read_json(url)
print(df)
print('\n')
#head
df.head(4)
print('\n')
#tail
df.tail(3)
print('\n')



#Excel
print("_____EXCEL_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.xlsx"
df = pd.read_excel(url)
print(df)

_____CSV_____
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567


_____JSON_____
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

Conversion Of Files:-

In [ ]:
#CSV to Json
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.csv"
df = pd.read_csv(url)
df.to_json("file1.json")
print(df)

#Json to CSV

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

#Head() and Tail() Function

In [ ]:
import pandas as pd
print("_____CSV_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.csv"
df = pd.read_csv(url)
print(df)
print('\n')
#head
df.head()
df.head(-2)

#tail
df.tail()
df.tail(2)
df.tail(-2)

# only prints the last one if we not use print

_____CSV_____
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345

In [ ]:
import pandas as pd
print("_____CSV_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.csv"
df = pd.read_csv(url)
print(df)
print('\n')
#head with print
print("---HEAD---")
print(df.head(4))
print('\n')
#tail wirh print
print("---TAIL---")
print(df.tail(4))

# both can be displayed using print

_____CSV_____
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567


---HEAD---
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356


---TAIL---
       name  roll no
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

#Shape And Info

In [ ]:
import pandas as pd
print("_____CSV_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.csv"
df = pd.read_csv(url)
print(df)
print('\n')
df.shape # gives no. of rows and no. of columns --> (rows,columns)
print('\n')
df.info()
print('\n')
# only gives last output if we don't use print

_____CSV_____
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [ ]:
import pandas as pd
print("_____CSV_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.csv"
df = pd.read_csv(url)
print(df)
print('\n')
# after using print
print("----shape----")
print(df.shape)
print('\n')
print("----info----")
print(df.info())
print('\n')
print("----info(verbose=False)----")
print(df.info(verbose=False))
# verbose hides the information

_____CSV_____
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567


----shape----
(5, 2)


----info----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes
None


----info(verbose=False)----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 2 entries, name to roll no
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes
None

#Rename

In [92]:
import pandas as pd
print("_____JSON_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.json"
df = pd.read_json(url)
# print(df)
# print('\n')
df.rename(columns={"name":"Student_Name"},inplace=True)
print(df)

_____JSON_____
  Student_Name  roll no
0      dheeraj      123
1        kunal     1234
2     abhishek    12345
3      praveen    12356
4       anjali  1234567

#Describe

In [93]:
import pandas as pd
print("_____JSON_____")
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file1.json"
df = pd.read_json(url)
print(df)
print('\n')
df.describe()

_____JSON_____
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

            roll no
count  5.000000e+00
mean   2.521250e+05
std    5.492329e+05
min    1.230000e+02
25%    1.234000e+03
50%    1.234500e+04
75%    1.235600e+04
max    1.234567e+06

Question --> Apply All The Above Concepts On Given Data

In [108]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
print("---------------Question---------------")
df = pd.DataFrame(data)

print(df)
print('\n')
#shape
print("_____SHAPE_____")
print(df.shape)
#rename
print('\n')
print("_____RENAME_____")
df.rename(columns={"Name":"Emp_Name"},inplace=True)
print(df)
print('\n')
#info
print("_____INFO_____")
df.info()
print('\n')
#head
print("_____HEAD_____")
print(df.head(2))
print('\n')
#tail
print("_____TAIL_____")
print(df.tail(2))
print('\n')
#describe
print("_____DESCRIBE_____")
df.describe()

---------------Question---------------
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3


_____SHAPE_____
(6, 5)


_____RENAME_____
   Emp_ID Emp_Name Department  Salary  Experience
0     101     Amit         IT   50000           2
1     102     Riya         HR   45000           3
2     103      Raj    Finance   60000           5
3     104     Sara         IT   55000           4
4     105     John      Sales   48000           1
5     106     Neha         HR   52000           3


_____INFO_____
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      6 non-null      int64
 1   Emp_Name    6 non-null      object
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes


_____HEAD_____
   Emp_ID Emp_Name Department  Salary  Experience
0     101     Amit         IT   50000           2
1     102     Riya         HR   45000           3


_____TAIL_____
   Emp_ID Emp_Name Department  Salary  Experience
4     105     John      Sales   48000           1
5     106     Neha         HR   52000           3


_____DESCRIBE_____

           Emp_ID        Salary  Experience
count    6.000000      6.000000    6.000000
mean   103.500000  51666.666667    3.000000
std      1.870829   5316.640543    1.414214
min    101.000000  45000.000000    1.000000
25%    102.250000  48500.000000    2.250000
50%    103.500000  51000.000000    3.000000
75%    104.750000  54250.000000    3.750000
max    106.000000  60000.000000    5.000000